[project]
name = "work-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fpdf>=1.7.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pathspec>=0.12.1",
    "rich>=13.9.4",
]
